//
//  HumanActionHelper.m
//  SenseMeEffects
//
//  Created by 马浩萌 on 2024/1/8.
//  Copyright © 2024 SoftSugar. All rights reserved.
//

#import "HumanActionHelper.h"
#import "st_mobile_human_action.h"

@implementation HumanActionHelper

+(NSDictionary *)detectConfigMapping {
    NSDictionary *featureMapping = @{
        @(ST_MOBILE_FACE_DETECT): @"ST_MOBILE_FACE_DETECT",
        @(ST_MOBILE_EYE_BLINK): @"ST_MOBILE_EYE_BLINK",
        @(ST_MOBILE_MOUTH_AH): @"ST_MOBILE_MOUTH_AH",
        @(ST_MOBILE_HEAD_YAW): @"ST_MOBILE_HEAD_YAW",
        @(ST_MOBILE_HEAD_PITCH): @"ST_MOBILE_HEAD_PITCH",
        @(ST_MOBILE_BROW_JUMP): @"ST_MOBILE_BROW_JUMP",
        @(ST_MOBILE_FACE_LIPS_UPWARD): @"ST_MOBILE_FACE_LIPS_UPWARD",
        @(ST_MOBILE_FACE_LIPS_POUTED): @"ST_MOBILE_FACE_LIPS_POUTED",
        @(ST_MOBILE_HAND_DETECT): @"ST_MOBILE_HAND_DETECT",
        @(ST_MOBILE_DETECT_HAND_GESTURE): @"ST_MOBILE_DETECT_HAND_GESTURE",
        @(ST_MOBILE_DETECT_HAND_SSH): @"ST_MOBILE_DETECT_HAND_SSH",
        @(ST_MOBILE_SEG_BACKGROUND): @"ST_MOBILE_SEG_BACKGROUND",
        // 只为ST_MOBILE_FACE_240_DETECT或ST_MOBILE_DETECT_EXTRA_FACE_POINTS中的一个提供映射
        @(ST_MOBILE_FACE_240_DETECT): @"ST_MOBILE_FACE_240_DETECT / ST_MOBILE_DETECT_EXTRA_FACE_POINTS",
        @(ST_MOBILE_DETECT_EYEBALL_CENTER): @"ST_MOBILE_DETECT_EYEBALL_CENTER",
        @(ST_MOBILE_DETECT_EYEBALL_CONTOUR): @"ST_MOBILE_DETECT_EYEBALL_CONTOUR",
        @(ST_MOBILE_BODY_KEYPOINTS): @"ST_MOBILE_BODY_KEYPOINTS",
        @(ST_MOBILE_BODY_CONTOUR): @"ST_MOBILE_BODY_CONTOUR",
        @(ST_MOBILE_SEG_HAIR): @"ST_MOBILE_SEG_HAIR",
        @(ST_MOBILE_DETECT_TONGUE): @"ST_MOBILE_DETECT_TONGUE",
        @(ST_MOBILE_SEG_HEAD): @"ST_MOBILE_SEG_HEAD",
        @(ST_MOBILE_SEG_SKIN): @"ST_MOBILE_SEG_SKIN",
        @(ST_MOBILE_SEG_FACE_OCCLUSION): @"ST_MOBILE_SEG_FACE_OCCLUSION",
        @(ST_MOBILE_DETECT_FOOT): @"ST_MOBILE_DETECT_FOOT",
        @(ST_MOBILE_BODY_ACTION5): @"ST_MOBILE_BODY_ACTION5 / ST_MOBILE_SEG_TROUSER_LEG",
        @(ST_MOBILE_DETECT_FINGER): @"ST_MOBILE_DETECT_FINGER",
        @(ST_MOBILE_DETECT_HAND_SKELETON_KEYPOINTS): @"ST_MOBILE_DETECT_HAND_SKELETON_KEYPOINTS",
        @(ST_MOBILE_DETECT_HAND_SKELETON_KEYPOINTS_3D): @"ST_MOBILE_DETECT_HAND_SKELETON_KEYPOINTS_3D",
        @(ST_MOBILE_SEG_MULTI): @"ST_MOBILE_SEG_MULTI",
        @(ST_MOBILE_DETECT_GAZE): @"ST_MOBILE_DETECT_GAZE",
        @(ST_MOBILE_DETECT_DYNAMIC_GESTURE): @"ST_MOBILE_DETECT_DYNAMIC_GESTURE",
        @(ST_MOBILE_DETECT_AVATAR_HELPINFO): @"ST_MOBILE_DETECT_AVATAR_HELPINFO",
        @(ST_MOBILE_DETECT_FACE_S_COLOR): @"ST_MOBILE_DETECT_FACE_S_COLOR",
        @(ST_MOBILE_DETECT_HAIR_COLOR): @"ST_MOBILE_DETECT_HAIR_COLOR",
        @(ST_MOBILE_BODY_KEYPOINTS_3D): @"ST_MOBILE_BODY_KEYPOINTS_3D",
        @(ST_MOBILE_DETECT_EAR): @"ST_MOBILE_DETECT_EAR",
        @(ST_MOBILE_DETECT_FOREHEAD): @"ST_MOBILE_DETECT_FOREHEAD",
        @(ST_MOBILE_DETECT_FACE_MESH): @"ST_MOBILE_DETECT_FACE_MESH",
        @(ST_MOBILE_DETECT_MOUTH_PARSE): @"ST_MOBILE_DETECT_MOUTH_PARSE",
        @(ST_MOBILE_DETECT_HEAD): @"ST_MOBILE_DETECT_HEAD",
        @(ST_MOBILE_DETECT_HEAD_MESH): @"ST_MOBILE_DETECT_HEAD_MESH",
        @(ST_MOBILE_DETECT_UPBODY_AVATAR): @"ST_MOBILE_DETECT_UPBODY_AVATAR",
        @(ST_MOBILE_SEG_SKY): @"ST_MOBILE_SEG_SKY",
        @(ST_MOBILE_DEPTH_ESTIMATION): @"ST_MOBILE_DEPTH_ESTIMATION",
        @(ST_MOBILE_NAIL_DETECT): @"ST_MOBILE_NAIL_DETECT",
        @(ST_MOBILE_SEG_CLOTH): @"ST_MOBILE_SEG_CLOTH",
        @(ST_MOBILE_SEG_GREEN): @"ST_MOBILE_SEG_GREEN",
        @(ST_MOBILE_WRIST_DETECT): @"ST_MOBILE_WRIST_DETECT",
        @(ST_MOBILE_DETECT_BODY_MESH): @"ST_MOBILE_DETECT_BODY_MESH",
        @(ST_MOBILE_FACE_DETECT_FULL): @"ST_MOBILE_FACE_DETECT_FULL",
        @(ST_MOBILE_HAND_DETECT_FULL): @"ST_MOBILE_HAND_DETECT_FULL",
        @(ST_MOBILE_BODY_DETECT_FULL): @"ST_MOBILE_BODY_DETECT_FULL"
    };

    return featureMapping;
}

@end
